name: Deploy with New Relic Change Tracking
on:
  push:
    branches:
      - main  # Change to your main branch or the branch you want to trigger on
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14  # Adjust the Node.js version as needed
      - name: Install dependencies
        run: |
          npm install  # Use your package manager's command if not npm
      - name: Build
        run: |
          npm run build  # Replace with your build command/script
      - name: Deploy to New Relic
        run: |
          APPLICATION_NAME="myphp-app"  # Replace with your New Relic application name
          REVISION=$(74a8670e6c84c1de5478a8e7647c85a8111e03fc)  # Use the current Git commit SHA
          NEWRELIC_API_KEY="NRAK-59A6OKHCGZ3PFY9S5Q91K5YI7KG"  # Replace with your New Relic API key
          # Install the New Relic CLI
          npm install -g newrelic
          # Authenticate with your New Relic account (you may need to run 'newrelic auth' separately)
          # newrelic auth
          # Record the deployment in New Relic
          newrelic deployments \
            --appname="$APPLICATION_NAME" \
            --revision="$REVISION" \
            --user="$GITHUB_ACTOR" \
            --description="Deployment from GitHub Actions" \
            --apikey="$NEWRELIC_API_KEY"
